### ISSUE TITLE
Error in Ops.data.frame

### ISSUE THREAD

**Issue by dongjt0727** [rondolab/MR-PRESSO#2]
I want use it with my data, but always failed like this "Error in Ops.data.frame(data[, c(BetaOutcome, BetaExposure)], sign(data[,  : 
  ‘*’ only defined for equally-sized data frames"

**Comment by rondolab** [comment]
Hi, 
could you tell me more about the command you ran? 
Quick question, are you defining the arguments BetaOutcome, BetaExposure and SdOutcome, SdExposure as characters referring to the column names of the dataframe defined by the argument data.
Best.

**Comment by jean997** [comment]
I have also gotten this error. I am attaching some data that reproduces it. 
[test_data_mrp.tsv.gz](https://github.com/rondolab/MR-PRESSO/files/2621470/test_data_mrp.tsv.gz)
The commands I used are

```
library(readr)
library(MRPRESSO)
dat <- read_tsv("test_data_mrp.tsv.gz")
x <- mr_presso(BetaOutcome = "beta_hat_2", BetaExposure = "beta_hat_1",
              SdOutcome = "seb2", SdExposure = "seb1", OUTLIERtest = TRUE,
              DISTORTIONtest = TRUE, data = dat,
              NbDistribution = 1000,  SignifThreshold = 0.05)
```

**Comment by jean997** [comment]
I think the problem comes from using `tbl_df` objects. I believe that as written, the `mr_presso` function is only compatible with `data.frame`.

**Comment by rondolab** [comment]
Thank you for your feedback, this is indeed the issue. The analysis runs if "dat" is converted to data.frame.
`x <- mr_presso(BetaOutcome = "beta_hat_2", BetaExposure = "beta_hat_1",
              SdOutcome = "seb2", SdExposure = "seb1", OUTLIERtest = TRUE,
              DISTORTIONtest = TRUE, data = as.data.frame(dat),
              NbDistribution = 1000,  SignifThreshold = 0.05)`
We have added an error to avoid this issue.
Best.

**Comment by z-bluesky** [comment]
I had the same problem when running the vlnplot and dimplot functions in the Seurat package：
`VlnPlot(scRNAlist[[i]], features = c("nFeature_RNA"))`
Error in Ops.data.frame(guide_loc, panel_loc) : 
  ‘==’ only defined for equally-sized data frames
  But I use this line of code, restart the session and it works, finally!！！！
`remotes::install_github("thomasp85/patchwork")`
