### ISSUE TITLE
Error in xj[i] : invalid subscript type 'list'

### ISSUE THREAD

**Issue by frankwendt5010** [rondolab/MR-PRESSO#4]
I just tried running mr_presso and get the following error. I've already performed the analysis on some different data files, formatted the same, and did not get an error. Any ideas how to fix this?

Error in xj[i] : invalid subscript type 'list'

**Comment by rondolab** [comment]
Hi,
this is probably an error we haven't encountered yet. Would you be able to provide the dataset (or a similar one) for us to replicate the error?
Thank you very much.
Best.

**Comment by DanielaZanetti** [comment]
Hi
I've just got the same error. Any idea about how can I solve this issue?

Best
Daniela

**Comment by rondolab** [comment]
Hi,
this issue has been fixed and was coming from the fact that all SNPs were detected as outliers at the specified significance threshold.
Best.
